# Create it using "eksctl create cluster -f dev.yaml"

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mantis-simon-dev
  region: us-west-2

managedNodeGroups:
  - name: benchmark-nodes
    desiredCapacity: 3
    instanceType: m5.8xlarge # 32 cores 128 G