# Create it using "eksctl create cluster -f dev.yaml"

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mantis-simon-dev
  region: us-west-2

managedNodeGroups:
  - name: managed-nodes
    desiredCapacity: 3
    instanceType: t2.2xlarge
