apiVersion: batch/v1
kind: Job
metadata:
  name: mantis-load-gen
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: load-gen
          image: fissure/py:latest
          imagePullPolicy: Always
          command:
            [
              "mantis",
              "load-gen",
              "--redis-ip",
              "redis-service",
              "--redis-port",
              "7000",
              "--load",
              "./debug.npy",
            ]
          resources:
            requests:
              cpu: 500m
              memory: 0.5Gi
            limits:
              cpu: 1
              memory: 0.5Gi
