apiVersion: v1
kind: Pod
metadata:
  name: mantis-metric-monitor
spec:
  containers:
    - name: metric-monitor
      image: fissure/py:latest
      imagePullPolicy: Always
      command:
        [
          "mantis",
          "metric-monitor",
          "--redis-ip",
          "redis-service",
          "--redis-port",
          "7000",
        ]
      resources:
        requests:
          cpu: 0.5
          memory: 0.5Gi
        limits:
          cpu: 1
          memory: 0.5Gi
