apiVersion: v1
kind: ResourceQuota
metadata:
  name: job-concurrency
spec:
  hard:
    requests.mantis.com/concurrent: 1
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: controller-role
subjects:
  - kind: ServiceAccount
    name: controller-role
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-role
