apiVersion: apps/v1
kind: Deployment
metadata:
  name: mantis-worker
spec:
  replicas: 5
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      terminationGracePeriodSeconds: 3600 # An hour
      containers:
        - name: worker
          lifecycle:
            preStop:
              exec:
                command: ["kill", "-s", "HUP", "1"]
          image: fissure/py:latest
          imagePullPolicy: Always
          # ENV to be filled.
          command:
            [
              "mantis",
              "consume",
            ]
          resources:
            requests:
              cpu: 1000m
              memory: 0.5Gi
            limits:
              cpu: 1000m
              memory: 2.5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: mantis-frac-worker
  labels:
    name: mantis-frac-worker
spec:
  containers:
    - name: mantis-frac-worker
      image: fissure/py:latest
      imagePullPolicy: Always
      # ENV to be filled.
      command:
        [
          "mantis",
          "consume",
          "--is-fractional",
        ]
      resources:
        requests:
          cpu: 1000m
          memory: 0.5Gi
        limits:
          cpu: 1000m
          memory: 2.5Gi