apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mantis-controller
    spec:
      serviceAccountName: controller-role
      containers:
        - name: mantis-controller
          imagePullPolicy: Always
          image: fissure/controller:latest
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: controller-role
subjects:
  - kind: ServiceAccount
    name: controller-role
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-role
