apiVersion: batch/v1
kind: Job
metadata:
  name: mantis-load-gen
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: load-gen
          image: fissure/py:latest
          imagePullPolicy: Always
          command:
            [
              "mantis",
              "load-gen",
            ]
          resources:
            requests:
              cpu: 500m
              memory: 0.5Gi
            limits:
              cpu: 1
              memory: 0.5Gi
          volumeMounts:
          - mountPath: /data
            name: data-volume
      initContainers:
        - name: copy-traces
          image: fissure/traces:latest
          command: ["sh", "-c", "cp -r /data/* /trace-data/"]
          volumeMounts:
          - mountPath: /trace-data
            name: data-volume
      volumes:
        - name: data-volume
          hostPath:
            path: /trace-data
            type: DirectoryOrCreate
